export const ActionConstants = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    ADD_TO_CART: 'ADD_TO_CART',
    INCREMENT_QNT: 'INCREMENT_QNT',
    DECREMENT_QNT: 'DECREMENT_QNT',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    ORDER_BY_NAME: 'ORDER_BY_NAME',
    ORDER_BY_PRICE: 'ORDER_BY_PRICE',
}